trainer:
  gpus: 1
  min_epochs: 20
  max_epochs: 100
  benchmark: True

experiment:
  task: "oscd"
  module:
    loss: "ce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 26
    num_classes: 2
    num_filters: 256
    ignore_zeros: False
  datamodule:
    root_dir: "data"
    batch_size: 2
    num_workers: 0
    val_split_pct: 0.0
