experiment:
  task: "oscd"
  module:
    loss: "bce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 6
    verbose: false
    in_channels: 13
    num_classes: 1
    num_filters: 256
    ignore_zeros: False
  datamodule:
    root_dir: "tests/data/oscd"
    batch_size: 32
    num_workers: 0
